shell_integration enabled

cursor_trail 1

pixel_scroll yes
momentum_scroll 0.96

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

map kitty_mod+t new_tab_with_cwd
map kitty_mod+enter new_window_with_cwd

map shift+space>o>g launch --cwd=current lazygit
map shift+space>o>n launch --cwd=~/Notes/ sh -c 'nvim ~/Notes/journal/$(date +%Y-%m-%d).md'
map shift+space>o>d launch --cwd=~/.local/share/chezmoi/
