return {
  "nvim-treesitter/nvim-treesitter",
  name = "nvim-tressitter",
  build = ":TSUpdate",
  opts = {
    indent = { enable = true },
    highlight = { enable = true },
    folds = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "comment",
      "cpp",
      "css",
      "c_sharp",
      "csv",
      "diff",
      "html",
      "java",
      "javadoc",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "just",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "nix",
      "printf",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    }
  }
  -- TODO: Need to add keybinds for using treesitter for selections.
}
